config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  get 'events/index'
  get 'events/show'
  get 'events/new'
  get 'events/create'
  get 'events/edit'
  get 'events/update'
  get 'events/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'events#index'

  resources :events
  resources :static_pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    after_create :attendance_send
      
    def attendance_send
        admin = self.event.admin
        user = self.user
        AttendanceMailer.attendance_email(admin, user).deliver_now
    end

    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :users, through: :attendances
    belongs_to :admin, class_name: "User"
    validates :start_date, presence: true #, No create of update before actual date
    validates :duration, presence: true #, positif, multiple of 5 and in minutes
    validates :title, presence: true, length: { in: 5..140 }
    validates :description, presence: true, length: { in: 10..1000 }
    validates :price, presence: true, length: { in: 0..1000 }
    validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send
      
    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end

    has_many :attendances
    has_many :events, through: :attendances
    has_many :attendances, foreign_key: 'admin_id', class_name: 'Attendance'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @all_events = Event.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1>Tous les évènements</h1>

<div class="container">

    <div class="row">
    <h1>Bienvenue !</h1>
    <p>Tu trouvera ici tous les évènements</p>
    <!-- Afficher la liste des events -->
        <% @all_events.each do |event| %>
        <div class="card" style="width: 18rem;">
    
            <div class="card-body">
                <h5 class="card-title">Event :  <%= event.title %></h5>
                <p class="card-text"> <%= event.description %></p>
                <a href="/gossips/<%= event.id %>" class="btn btn-primary">Voir l'event<%= event.id %></a>
            </div>
            
        </div>
        <% end %>
    <a href= "/events/new" class="btn btn-primary">Créer un event</a>
    </div>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>